### PR TITLE
feature/WDP191000-11-rwd-main-menu

### PR DESCRIPTION
**Pull request by izabela-d**
The problem:
RWD css styles don't work properly

The solution:
- Changed order of `.menu-bar` columns
- Added RWD styles
- Extracted variables for "sm", "md", "lg", "xl" variables for responsive design  

Mobile:
mobile
`.search-form .category` select is not visible because I there is not enough space

Big mobile:
big-mobile

Tablet:
tablet

Desktop:
Screenshot from 2019-11-04 23-11-12

### CODE REVIEW

**Comment by matwjablonski** [comment]
please resolve conflicts

**Comment by izabela-d** [comment]
Conflicts resolved

**Comment by izabela-d** [comment]
@JagodaBodnar  I can't reproduce this bug. What browser do you use and what is the screen width when you see the problem?

**Comment by JagodaBodnar** [comment]
@JagodaBodnar I can't reproduce this bug. What browser do you use and what is the screen width when you see the problem?
I use chrome Google Chrome Version 78.0.3904.97 (Official Build) (64-bit).
It happens for 764 and less so its kinda only when sandwich appears.
Maybe someone else could take a look at that too.

**Comment by JagodaBodnar** [comment]
From what I saw when i pulled code if you gonna add .collapsing{ height: 0px!important;} then problem disappears however I am not sure if that's the right solution to this problem.

**Comment by izabela-d** [comment]
Naprawiłam problem z kanapką. 
Gdy klikasz na kanapkę JS od bootstrap nakłada do elementu menu-rolled atrybut `style= height:465px`. Dlatego dla wersji mobilnej musiałam dać !important.

**Comment by JagodaBodnar** [comment]
Works great now! Awesome! Approved :)

**Pull request merged**
